name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (64-bit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Verify environment
        run: |
          python -c "import struct, sys; print('Python bits:', struct.calcsize('P')*8, sys.version)"
          python -c "import pandas, fitz, pyodbc; print('pandas', pandas.__version__); print('fitz OK'); print('pyodbc OK')"

      - name: Build EXE
        run: |
          python -m PyInstaller --onefile --noconsole src\\pdf_to_access_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf_to_access_app-win64
          path: dist\\pdf_to_access_app.exe
