# .github/workflows/build-win32.yml
name: Build 32-bit EXE

on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x86'
      - run: |
          pip install -r requirements.txt
          pyinstaller --onefile --noconsole src/pdf_to_access_app.py
      - uses: actions/upload-artifact@v4
        with:
          name: pdf_to_access_app-win32
          path: dist/pdf_to_access_app.exe
