name: Build Windows EXE

#on:
#  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install pymupdf pandas openpyxl pyyaml pyodbc pyinstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole src/pdf_to_access_app.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf_to_access_app
          path: dist/pdf_to_access_app.exe
